spring:
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dluck.synology.me:3306/shop?serverTimezone=Asia/Shanghai
    username: shop
    password: 27HEZ6xWAnZiHRt4
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  mvc:
    static-path-pattern: /static/**