spring:
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://example:3306/shop?serverTimezone=Asia/Shanghai
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  mvc:
    static-path-pattern: /static/**
